image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - scala-lang.scala
    - scalameta.metals

ports:
  - port: 8212
    onOpen: ignore
  # - port: 9411

tasks:
- name: init metals and bloop
  init: sbt bloopInstall
  command: zsh
# - before: cd ~/zipkin
#   command: java -jar zipkin.jar
