image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - scala-lang.scala
    - scalameta.metals

ports:
  - port: 8212
    onOpen: ignore
  # - port: 9411

tasks:
- name: Install and build
  init: |
    sbt -Dbloop.export-jar-classifiers=sources bloopInstall
  command: |
    bloop about
    bloop projects | xargs bloop compile --watch
# - before: cd ~/zipkin
#   command: java -jar zipkin.jar
