addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
//addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.29")
//addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.9")

addSbtPlugin("com.dwijnand"   % "sbt-dynver"     % "4.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"   % "3.7")
addSbtPlugin("com.geirsson"   % "sbt-ci-release" % "1.3.2")
//addSbtPlugin("com.jsuereth"     % "sbt-pgp"        % "2.0.0-M2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"        % "1.0.0")
addSbtPlugin("com.47deg"        % "sbt-microsites" % "0.9.6")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"   % "2.0.5")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"  % "1.6.0")
