addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
//addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.5.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.26")
//addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.8")
//libraryDependencies += "org.scala-js" %% "scalajs-env-jsdom-nodejs" % "1.0.0-M3"
//addSbtPlugin("org.scala-sbt"  % "sbt-autoversion" % "1.0.0")
//addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.2.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.3")
//addSbtPlugin("com.jsuereth"   % "sbt-pgp"         % "1.1.2-1")
//addSbtPlugin("io.get-coursier" % "sbt-coursier"   % "1.1.0-M9")
addSbtPlugin("com.47deg"     % "sbt-microsites" % "0.7.27")
addSbtPlugin("com.geirsson"  % "sbt-scalafmt"   % "1.5.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage"  % "1.6.0-M5")
