addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
//addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.3.1")
//addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.9")

addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
//addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"   % "3.8")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.7")
//addSbtPlugin("com.jsuereth"     % "sbt-pgp"        % "2.0.0-M2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"        % "1.0.0")
addSbtPlugin("com.47deg"        % "sbt-microsites" % "1.3.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"   % "2.4.2")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"  % "1.6.1")
