on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches:
      - main
    types:
      - completed
name: Semantic Release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        env:
          cache-name: cache-node-modules
        with:
          node-version: 16
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Plugins
        run: >
          npm install semantic-release &&
          npm install @semantic-release/changelog -D &&
          npm install @semantic-release/git -D
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
